# Generated by Django 4.2.20 on 2025-04-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questionnaire_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='suffering_level',
            field=models.CharField(max_length=50),
        ),
    ]
