# Generated by Django 4.2.20 on 2025-04-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_questionnaire_suffering_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3),
        ),
    ]
