# Generated by Django 4.2.20 on 2025-04-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3),
        ),
    ]
